apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-app-html
  labels:
    app: mi-app-html
spec:
  replicas: 2
  progressDeadlineSeconds: 20   # <- CLAVE: plazo corto de progreso
  selector:
    matchLabels:
      app: mi-app-html
  template:
    metadata:
      labels:
        app: mi-app-html
    spec:
      containers:
        - name: mi-app-html
          image: shovelman/mi-app-html:v1
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 9999      # puerto incorrecto para forzar fallo
            initialDelaySeconds: 2
            periodSeconds: 3
