apiVersion: v1
kind: Service
metadata:
  name: mi-app-html
  labels:
    app: mi-app-html
spec:
  type: NodePort
  selector:
    app: mi-app-html
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30081
